apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opszero.fullname" . }}-celery
  labels:
    {{- include "opszero.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opszero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opszero.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "--app=opszero.celery", "worker", "--loglevel=info", "--concurrency=1"]
          envFrom:
            - secretRef:
                name: {{ template "opszero.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "opszero.fullname" . }}-celery
  labels:
    {{- include "opszero.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "opszero.fullname" . }}-celery
    kind: Deployment
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  cooldownPeriod: 120
  triggers:
  - type: redis
    metadata:
      address: "{{ .Values.secrets.REDIS_URL }}"
      databaseIndex: "1"
      listName: celery
      listLength: "5"
  - type: cpu
    metadata:
      type: Utilization
      value: {{ .Values.autoscaling.targetCPUUtilizationPercentage | quote }}
  - type: memory
    metadata:
      type: Utilization
      value: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | quote }}