{{- range $ep := .Values.externalEndpoints }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "opszero.fullname" $ }}-{{ $ep.name }}-external
  labels:
      {{- include "opszero.labels" $ | nindent 4 }}-{{ $ep.name }}
spec:
  ports:
    {{- range $p := $ep.ports }}
    - protocol: {{ $p.protocol }}
      port: {{ $p.port }}
      targetPort: {{ $p.port }}
    {{ end }}

---

kind: Endpoints
apiVersion: v1
metadata:
  name: {{ include "opszero.fullname" $ }}-{{ $ep.name }}-external
subsets:
  - addresses:
      {{- toYaml $ep.addresses | nindent 6 }}
    ports:
      {{- range $p := $ep.ports }}
      - port: {{ $p.port }}
      {{- end }}
---
{{ end }}
