{{- range $app := .Values.externals }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opszero.fullname" $ }}-{{ $app.name }}
  labels:
    {{- include "opszero.labels" $ | nindent 4 }}-{{ $app.name }}
spec:
  type: ExternalName
  selector:
    {{- include "opszero.selectorLabels" $ | nindent 4 }}-{{ $app.name }}
  externalName: {{ $app.cname }}

{{- if $app.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opszero.fullname" $ }}-{{ $app.name }}
  labels:
    {{- include "opszero.labels" $ | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $app.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- with $app.ingress.hosts }}
    {{- range $host := . }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "opszero.fullname" $ }}-{{ $app.name }}
              port:
                number: {{ $host.port }}
          {{- end }}
    {{- end }}
    {{- end }}
  tls:
    - hosts:
    {{- range $app.ingress.hosts }}
        - {{ .host }}
    {{- end }}
      secretName: {{ include "opszero.fullname" $ }}-{{ $app.name }}-tls
{{- end -}}
{{- end }}
