{{- $dot := . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "opszero.fullname" . }}-db-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "opszero.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        name: {{ include "opszero.fullname" . }}-db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "opszero.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: {{ template "opszero.fullname" . }}