apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "opszero.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "opszero.labels" . | nindent 4 }}
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote -}}
{{- end }}
data:
{{- range $k, $v := .Values.secrets64 }}
  {{ $k }}: {{ $v | quote -}}
{{- end }}